CREATE TABLE IF NOT EXISTS news_embeddings (
	news_id INTEGER PRIMARY KEY,
	model   TEXT NOT NULL,
	vector  BLOB NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (news_id) REFERENCES news(id) ON DELETE CASCADE
);
