// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchTopics(arg1) {
  return window['go']['main']['App']['FetchTopics'](arg1);
}

export function GetNews() {
  return window['go']['main']['App']['GetNews']();
}
