// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewFeed(arg1, arg2) {
  return window['go']['main']['App']['AddNewFeed'](arg1, arg2);
}

export function DeleteFeed(arg1) {
  return window['go']['main']['App']['DeleteFeed'](arg1);
}

export function FetchFeeds() {
  return window['go']['main']['App']['FetchFeeds']();
}

export function FetchTopics(arg1) {
  return window['go']['main']['App']['FetchTopics'](arg1);
}

export function GetNews() {
  return window['go']['main']['App']['GetNews']();
}

export function GetStoriesFromCentroid(arg1) {
  return window['go']['main']['App']['GetStoriesFromCentroid'](arg1);
}
