// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function FetchTopics(arg1:string):Promise<Array<store.Topic>>;

export function GetNews():Promise<void>;
