// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AddNewFeed(arg1:string,arg2:string):Promise<void>;

export function DeleteFeed(arg1:number):Promise<void>;

export function FetchFeeds():Promise<Array<store.Feed>>;

export function FetchTopics(arg1:string):Promise<Array<store.Topic>>;

export function GetNews():Promise<void>;

export function GetStoriesFromCentroid(arg1:string):Promise<Array<store.Story>>;
